#!/bin/bash

echo "[+] Remove from the Universe"

docker container stop core_db
docker container stop core_web

docker container rm core_db
docker container rm core_web

docker image rm core_web

echo "[+] Prune the system"

docker system prune -a --volumes